### ISSUE TITLE
Error when requesting registration code via yowsup

### ISSUE THREAD

**Issue by Cauchon** [akleemans/pokenotifier-whatsapp#1]
**This is the response I get when trying to request the code via yowsup using the instructions provided.**

`me$ sudo yowsup-cli registration --requestcode sms --phone {MYPHONENUMBER} --cc 1
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))`

**Comment by Cauchon** [comment]
The problem here is that MacOS comes with six pre-installed. Here is the solution.

`pip install awsebcli --upgrade --ignore-installed six`

**Comment by akleemans** [comment]
Nice, thanks for working that one out! A pity though the maps are not working anymore on any cloud based service... :-/
